/*===============================================================================================
 FSB Example
 Copyright (c), Firelight Technologies Pty, Ltd 2008-2011.
 
 This example demonstrates the usage of the FSB format, generated by the FSBank tool.
 It is simply a packed file format, with sounds contained within.  This is a cross platform
 format that is useful to keep the data format optimal for the platform you are targeting.
 (ie PS2, Xbox, Gamecube have native compression formats)
 ===============================================================================================*/

#import "fmod.hpp"
#import "fmod_errors.h"
#import <UIKit/UIKit.h>
//#import "../media/example.h"   /* Header with FSB indicies. */

@interface ViewController : UIViewController <UIPickerViewDelegate>
{
	UILabel        *time;
    UILabel        *status;
    UILabel        *channels;
    UIPickerView   *subsoundpicker;
  	NSMutableArray *subsoundpickerdata;
    NSTimer        *timer;

    FMOD::System   *system;
    FMOD::Sound    *fsb;
    FMOD::Channel  *channel;
    int            numsubsounds;
}

@property (nonatomic, retain) IBOutlet UILabel      *time;
@property (nonatomic, retain) IBOutlet UILabel      *status;
@property (nonatomic, retain) IBOutlet UILabel      *channels;
@property (nonatomic, retain) IBOutlet UIPickerView *subsoundpicker;

- (IBAction)playSound:(id)sender;
- (void)timerUpdate:(NSTimer *)timer;

@end

